[tool.poetry]
name = "unnamed-space-game"
version = "0.1.0"
description = ""
authors = ["Bezruc"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
fastapi = "^0.114.2"
schedule = "^1.2.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
